import { themeHead, themeButton, themeScript } from './theme';
import { geistStyles } from './geist';
import { simulatorModels } from '../lib/models';

export const chatPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Empathetic Harness · Chat & reports</title>
${themeHead}<link rel="preload" href="/fonts/geist-sans-1.7.2.woff2" as="font" type="font/woff2" crossorigin><style>${geistStyles}</style></head><body>
<header><div class="brand"><span class="brand-icon" aria-hidden="true"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></svg></span><div><strong>Empathetic Harness</strong><small>Simulations / Reports</small></div></div><div class="header-actions">${themeButton}<button id="signout" class="hidden">Sign out</button></div></header>
<section id="login" class="login"><p class="eyebrow">User simulation</p><h1>Test your app.<br>See the evidence.</h1><p class="muted">Run a user journey and review what happened, with screenshots and a saved report.</p><form id="login-form"><label for="password">Operator password</label><input id="password" type="password" autocomplete="current-password" required><p id="login-error" class="error" role="alert"></p><button class="primary" type="submit">Unlock simulator</button></form></section>
<div id="workspace" class="shell hidden"><aside><div class="actions" style="margin-bottom:24px"><button id="new">New simulation</button></div><h2>Saved simulations</h2><div id="history"></div></aside><main><div id="notice" class="error" role="alert"></div><section id="conversation" aria-live="polite"></section>
<form id="composer" class="composer"><label for="model">Simulation model</label><select id="model">${simulatorModels.map(model => `<option value="${model.id}">${model.label}</option>`).join('')}</select><label for="task">What would you like the simulator to do?</label><textarea id="task" maxlength="12000" required placeholder="Describe the user’s goal, the steps you want explored, and what should count as success…"></textarea><label for="url">App URL</label><input id="url" type="url" placeholder="https://your-app.example (or use the configured app)"><details><summary>Try a built-in test app</summary><label for="scenario">Test scenario</label><select id="scenario"><option value="">Use my app</option><option value="success">Saved preference</option><option value="recovery">Recover from a stale shortcut</option><option value="false-success">Misleading success message</option></select></details><details><summary>Run limits and recovery</summary><p class="hint">Each message starts an independent simulation. You can close this tab while it runs. A PDF is saved here automatically, including partial evidence if a run stops early. AI analysis depends on model availability. Screenshots use 1024 × 640 pixels. Token-budget pauses save a note and continue automatically up to three times. Use Continue simulation to carry on in the same browser within 28 minutes of starting. Each turn has a 10-minute acting limit.</p></details><p class="hint">You can leave this page while a simulation runs. Its report is saved here.</p><button id="send" class="primary" type="submit">Run simulation</button></form>
<footer class="brand-footer">Built with eve · Deployed on Vercel</footer></main></div>
<script>
const el=id=>document.getElementById(id);let password='',runs=[],selected=new URLSearchParams(location.search).get('run'),timer=null,lastSignature='',signedIn=false;
const modelNames=${JSON.stringify(Object.fromEntries(simulatorModels.map(model => [model.id, model.label])))};
const labels={paused:'Paused · progress saved',running:'Simulation running',reporting:'Preparing PDF',ready:'Report ready',report_failed:'Report needs a retry'};
function progress(run){return run.status==='running'&&Date.now()-Date.parse(run.updatedAt||run.startedAt)>60000?'Waiting for progress':labels[run.status]}
function updateProgress(){const run=runs.find(r=>r.sessionId===selected);if(!run||run.status!=='running')return;const title=el('progress-title'),detail=el('progress-detail');if(title)title.textContent=progress(run);if(detail)detail.textContent=progress(run)==='Waiting for progress'?'No new activity since '+new Date(run.updatedAt||run.startedAt).toLocaleTimeString()+'. Checking the workflow; model requests may be retrying. You can stop and save the evidence.':run.activity;}
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...options.headers,authorization:'Bearer '+password},cache:'no-store'});if(!response.ok){let data;try{data=await response.json()}catch{}throw new Error(response.status===401?'Enter your operator password to continue.':data?.error||'Request failed ('+response.status+').')}return response}
function showError(error){el('notice').textContent=error.message}
function render(){
 el('history').replaceChildren();if(!runs.length)el('history').append(node('p','Your reports will appear here.','hint'));
 for(const run of runs){const b=node('button',undefined,'run'+(run.sessionId===selected?' active':''));b.append(node('strong',run.task),node('small',(run.model?(modelNames[run.model]||run.model)+' · ':'')+progress(run)+' · '+new Date(run.startedAt).toLocaleDateString()));b.onclick=()=>{selected=run.sessionId;render()};el('history').append(b)}
 const view=el('conversation');view.replaceChildren();const run=runs.find(r=>r.sessionId===selected);
 if(!run){view.append(node('h1','Run a user simulation.'),node('p','Describe a goal. The agent navigates your app, checks the outcome, and saves the evidence.','muted'));return}
 view.append(node('h1','Your simulation'));
 const user=node('div',undefined,'message user');user.append(node('div','You','label'),node('div',run.task,'prose'));view.append(user);
 const reply=node('div',undefined,'message');reply.dataset.state=run.status;reply.dataset.outcome=String(run.outcome);reply.append(node('div','Empathetic Harness','label'),node('div',run.status==='ready'?(run.reportKind==='evidence-only'?'Evidence report ready':run.outcome===true?'Task completed':run.outcome===false?'Task not completed':'Outcome unverified'):labels[run.status],'status'),node('div',run.rationale||run.activity,'prose'),node('div',(run.model?(modelNames[run.model]||run.model)+' · ':'')+run.actionCount+' actions · '+run.observationCount+' screenshots','metrics'));
 const actions=node('div',undefined,'actions');
 if(run.status==='paused'){const resume=node('button','Continue simulation','primary');resume.onclick=async()=>{resume.disabled=true;try{await api('/chat/runs/'+encodeURIComponent(run.sessionId)+'/continue',{method:'POST'});el('notice').textContent='Continuation requested. The simulation will take a fresh look and carry on.';await refresh()}catch(error){showError(error)}finally{resume.disabled=false}};actions.append(resume)}
 if(run.continuationNote){const note=node('details');note.append(node('summary','Saved continuation note'),node('div',run.continuationNote,'prose'));reply.append(note)}
 if(run.status==='ready'){const download=node('button','Download PDF','primary');download.onclick=async()=>{download.disabled=true;try{const response=await api('/chat/runs/'+encodeURIComponent(run.sessionId)+'/report.pdf');const url=URL.createObjectURL(await response.blob());const a=node('a');a.href=url;a.download='simulation-'+run.sessionId+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(error){showError(error)}finally{download.disabled=false}};actions.append(download)}
 if(run.status==='report_failed'||run.reportKind==='evidence-only'||(run.status==='reporting'&&Date.now()-Date.parse(run.updatedAt)>90000)){const retry=node('button',run.reportKind==='evidence-only'?'Retry AI analysis':'Retry PDF generation');retry.onclick=async()=>{retry.disabled=true;try{await api('/chat/runs/'+encodeURIComponent(run.sessionId)+'/report',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});await refresh()}catch(error){showError(error)}finally{retry.disabled=false}};actions.append(retry)}
 if(run.stopReason)reply.append(node('p',run.stopReason,'hint'));
 if(run.status==='running'||run.status==='paused'){reply.querySelector('.status').id='progress-title';reply.querySelector('.prose').id='progress-detail';const stop=node('button','Stop & save report','danger');stop.onclick=async()=>{stop.disabled=true;try{await api('/chat/runs/'+encodeURIComponent(run.sessionId)+'/stop',{method:'POST'});el('notice').textContent='Stop requested. The report will include the evidence collected so far.';await refresh()}catch(error){showError(error)}finally{stop.disabled=false}};actions.append(stop)}
 reply.append(actions);view.append(reply);updateProgress()
}
async function refresh(){const response=await api('/chat/runs');runs=(await response.json()).runs;const signature=JSON.stringify(runs);if(signature!==lastSignature){lastSignature=signature;render()}else updateProgress()}
async function start(){await refresh();signedIn=true;el('login').classList.add('hidden');el('workspace').classList.remove('hidden');el('signout').classList.remove('hidden');render();clearTimeout(timer);async function poll(){if(!signedIn)return;try{await refresh();el('notice').textContent=''}catch(error){showError(error)}if(signedIn)timer=setTimeout(poll,4000)}timer=setTimeout(poll,4000)}
el('login-form').onsubmit=async event=>{event.preventDefault();const button=event.submitter||el('login-form').querySelector('button');button.disabled=true;button.textContent='Unlocking…';password=el('password').value;el('login-error').textContent='';try{await start();el('password').value=''}catch(error){el('login-error').textContent=error.message}finally{button.disabled=false;button.textContent='Unlock simulator'}};
el('signout').onclick=()=>{signedIn=false;password='';clearTimeout(timer);runs=[];selected=null;lastSignature='';el('workspace').classList.add('hidden');el('signout').classList.add('hidden');el('login').classList.remove('hidden')};
el('new').onclick=()=>{selected=null;render();el('task').focus()};
el('composer').onsubmit=async event=>{event.preventDefault();el('send').disabled=true;el('send').textContent='Starting simulation…';el('notice').textContent='';try{const task=el('task').value.trim();const initialUrl=el('url').value.trim();const scenario=el('scenario').value;const response=await api('/chat/messages',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task,model:el('model').value,...(scenario?{scenario}:initialUrl?{initialUrl}:{})})});const data=await response.json();selected=data.sessionId;el('task').value='';await refresh();if(!runs.some(r=>r.sessionId===selected)){runs.unshift({sessionId:selected,task,model:el('model').value,status:'running',activity:'Starting the simulation',startedAt:new Date().toISOString(),actionCount:0,observationCount:0});render()}}catch(error){showError(error)}finally{el('send').disabled=false;el('send').textContent='Run simulation'}};
</script>${themeScript}</body></html>`;
